@base_url = http://localhost:3000
//
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMTVjNDk4NjYtMjg5Zi00Y2ZlLTkzM2QtYWY5YzI5ODczYmU3IiwidXNlcklkIjoxLCJpYXQiOjE3MDE5NjI4MjcsImV4cCI6MTcwMTk2NjQyN30.pE7bG3Jv1aDstXGrW_0l0GMXcOob1E3miUExuvlTghY


//inscription

POST {{base_url}}/api/auth/local/register
Content-Type: application/json

{
  "email": "nat7303@hotmail.fr",
  "username": "Nat",
  "password":"PasAdmin12"
}

### connexion
POST {{base_url}}/api/auth/local
Content-Type: application/json

{
  "identifier": "nat7303@hotmail.fr",
  "password": "PasAdmin12"
}

###
POST {{base_url}}/api/auth/local/logout
Authorization: Bearer {{token}}
Content-Type: application/json
###

GET {{base_url}}/api/users/me
Authorization: Bearer {{token}}

###
POST {{base_url}}/api/auth/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "currentPassword":"PasAdmin12",
    "password":"PasAdmin123",
    "passwordConfirmation":"PasAdmin123"
}

###
POST {{base_url}}/api/freegames
Content-Type: application/json

{
  "name": "patate",
  "description": "fqsgdbgfbwdSZfg",
  "image": "C:/Users/nat73/Pictures/Screenshots/A.png"
}


###
GET {{base_url}}/api/freegames
###
GET {{base_url}}/api/freegames/5
###

PUT {{base_url}}/api/freegames/1
Content-Type: application/json

{
    "data": {
    "name": "tata",
    "description": "zsdcfvg",
    "image": "C:/Users/nat73/Pictures/Screenshots/A.png"
}

}
###

POST {{base_url}}/api/officialGames
Content-Type: application/json                                         
Authorization: Bearer {{token}}

{
"data": {
  "name": "Patate_Premium",
  "description": "dfvfddfrd",
  "image": "zzsdcfvfd",
  "prix": 19.99
}
}
###
GET {{base_url}}/api/officialGames
Authorization: Bearer {{token}}
###
GET {{base_url}}/api/officialGames/1
Authorization: Bearer {{token}}
###

PUT {{base_url}}/api/officialgames/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "data": {
    "name": "tata",
    "description": "zsdcfvg",
    "image": "C:/Users/nat73/Pictures/Screenshots/A.png",
    "Prix": 16.12
}
}
###
DELETE {{base_url}}/api/officialGames/1
Authorization: Bearer {{token}}

###
DELETE {{base_url}}/api/freegames/2

###
GET {{base_url}}/api/officialGames
Authorization: Bearer {{token}}
###
GET {{base_url}}/api/officialGames/1
Authorization: Bearer {{token}}
###

PUT {{base_url}}/api/officialGames/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "data": {
    "name": "tata",
    "description": "zsdcfvg",
    "image": "C:/Users/nat73/Pictures/Screenshots/A.png",
    "Prix": 16.12
}
}