@base_url = http://localhost:3000

//inscription
POST {{base_url}}/api/auth/local/register
Content-Type: application/json

{
  "email": "nat7301@hotmail.fr",
  "username": "Naat",
  "password":"PasAdmin12"
}

###
//connexion
POST {{base_url}}/api/auth/local
Content-Type: application/json

{
  "identifier": "nat7301@hotmail.fr",
  "password": "PasAdmin123"
}

###
POST {{base_url}}/api/auth/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzAxNzczNTg3LCJleHAiOjE3MDQzNjU1ODd9._93jmG_92VMHMsBxxSZG-F_-sMJo922SrY64Dw6Q2cY
Content-Type: application/json
###

GET {{base_url}}/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzAxNzczNTg3LCJleHAiOjE3MDQzNjU1ODd9._93jmG_92VMHMsBxxSZG-F_-sMJo922SrY64Dw6Q2cY

###
POST {{base_url}}/api/auth/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAxNzgwOTc1LCJleHAiOjE3MDQzNzI5NzV9.0t8Co9_E8GmATpQvpDvnYTOSB77VgDYTO5oCu1fK-7U
Content-Type: application/json

{
    "currentPassword":"PasAdmin12",
    "password":"PasAdmin123",
    "passwordConfirmation":"PasAdmin123"
}

###
POST {{base_url}}/api/freeGames
Content-Type: application/json

{
  "name": "patate",
  "description": "fqsgdbgfbwdSZfg",
  "image": "C:/Users/nat73/Pictures/Screenshots/A.png"
}


###
GET {{base_url}}/api/freeGames
###
GET {{base_url}}/api/freeGames/5
###

PUT {{base_url}}/api/freeGames/5
Content-Type: application/json

{
    "data": {
    "nom": "tata",
    "description": "zsdcfvg",
    "image": "C:/Users/nat73/Pictures/Screenshots/A.png"
}
}
###

POST {{base_url}}/api/official-games
Content-Type: application/json                                         
Authorization: Bearer 76b0beeee596944c289e33690783343e24607f6d4cb056d636e5d62ca9b4a5230e62a894f2ee1cd38f1fa00ae2790994f0cbce110fb856f223b4b717f02b297155fc495a273062aafa7242f79a336d37ac4a635562844b4abd7dd7d43f4ee25b2b98c837af179bc5f2dd3de03059a92e41b2244b4ef7f41a8488745ac4b1287d

{
"data": {
  "Nom": "Patate_Premium",
  "Description": "dfvfddfrd",
  "Image": "zzsdcfvfd",
  "prix": 19.99
}
}
###
GET {{base_url}}/api/official-games
Authorization: Bearer 76b0beeee596944c289e33690783343e24607f6d4cb056d636e5d62ca9b4a5230e62a894f2ee1cd38f1fa00ae2790994f0cbce110fb856f223b4b717f02b297155fc495a273062aafa7242f79a336d37ac4a635562844b4abd7dd7d43f4ee25b2b98c837af179bc5f2dd3de03059a92e41b2244b4ef7f41a8488745ac4b1287d
###
GET {{base_url}}/api/official-games/1
Authorization: Bearer 76b0beeee596944c289e33690783343e24607f6d4cb056d636e5d62ca9b4a5230e62a894f2ee1cd38f1fa00ae2790994f0cbce110fb856f223b4b717f02b297155fc495a273062aafa7242f79a336d37ac4a635562844b4abd7dd7d43f4ee25b2b98c837af179bc5f2dd3de03059a92e41b2244b4ef7f41a8488745ac4b1287d
###

PUT {{base_url}}/api/official-games/1
Content-Type: application/json
Authorization: Bearer 76b0beeee596944c289e33690783343e24607f6d4cb056d636e5d62ca9b4a5230e62a894f2ee1cd38f1fa00ae2790994f0cbce110fb856f223b4b717f02b297155fc495a273062aafa7242f79a336d37ac4a635562844b4abd7dd7d43f4ee25b2b98c837af179bc5f2dd3de03059a92e41b2244b4ef7f41a8488745ac4b1287d

{
    "data": {
    "nom": "tata",
    "description": "zsdcfvg",
    "image": "C:/Users/nat73/Pictures/Screenshots/A.png",
    "Prix": 16.12
}
}
###
DELETE {{base_url}}/api/official-games/1
Authorization: Bearer 76b0beeee596944c289e33690783343e24607f6d4cb056d636e5d62ca9b4a5230e62a894f2ee1cd38f1fa00ae2790994f0cbce110fb856f223b4b717f02b297155fc495a273062aafa7242f79a336d37ac4a635562844b4abd7dd7d43f4ee25b2b98c837af179bc5f2dd3de03059a92e41b2244b4ef7f41a8488745ac4b1287d

###
//
POST {{base_url}}/api/official-games
Content-Type: application/json                                         
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAxNzg1ODY0LCJleHAiOjE3MDQzNzc4NjR9.IXBb-YiSAGM-xXipF7WPjdQUXTrvuOCfUoE3UI8ZYyc

{
"data": {
  "Nom": "Patate_Premium",
  "Description": "dfvfddfrd",
  "Image": "zzsdcfvfd",
  "prix": 19.99
}
}
###
GET {{base_url}}/api/official-games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAxNzg1ODY0LCJleHAiOjE3MDQzNzc4NjR9.IXBb-YiSAGM-xXipF7WPjdQUXTrvuOCfUoE3UI8ZYyc
###
GET {{base_url}}/api/official-games/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAxNzg1ODY0LCJleHAiOjE3MDQzNzc4NjR9.IXBb-YiSAGM-xXipF7WPjdQUXTrvuOCfUoE3UI8ZYyc
###

PUT {{base_url}}/api/official-games/1
Content-Type: application/json
Authorization: Bearer 76b0beeee596944c289e33690783343e24607f6d4cb056d636e5d62ca9b4a5230e62a894f2ee1cd38f1fa00ae2790994f0cbce110fb856f223b4b717f02b297155fc495a273062aafa7242f79a336d37ac4a635562844b4abd7dd7d43f4ee25b2b98c837af179bc5f2dd3de03059a92e41b2244b4ef7f41a8488745ac4b1287d

{
    "data": {
    "nom": "tata",
    "description": "zsdcfvg",
    "image": "C:/Users/nat73/Pictures/Screenshots/A.png",
    "Prix": 16.12
}
}
###
DELETE {{base_url}}/api/official-games/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAxNzg1ODY0LCJleHAiOjE3MDQzNzc4NjR9.IXBb-YiSAGM-xXipF7WPjdQUXTrvuOCfUoE3UI8ZYyc

